default: &default
  adapter: postgresql
  encoding: unicode
  database: eslite
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: db_user
  password: db_user

development:
  <<: *default
  database: eslite_development

test:
  <<: *default
  database: eslite_test

production:
  <<: *default
  database: eslite_production
